
services:
  qlish-backend:
    image: qlish-api:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MONGO_URI: ${MONGO_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      AVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - ./src:/app/src  # Bind-mount source code for live-reload
      - ./target/classes:/app/target/classes # Bind-mount compiled classes for live-reload
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  redis-data-dev:
